[package]
name = "jsrepl"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "0.311.0"
rustyline = { version = "14.0.0", features = ["with-file-history"] }
syntect = "5.2.0"
tokio = { version = "1.40.0", features = ["full"] }
